// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies;

/**
 * 
 */
public class DOB
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dOBMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestSuite.DOB";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		day("day"),
		month("month");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DOB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestSuite.DOB"));
	}

	protected DOB(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dOBMendixObject)
	{
		if (dOBMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestSuite.DOB", dOBMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestSuite.DOB");

		this.dOBMendixObject = dOBMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DOB.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testsuite.proxies.DOB initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testsuite.proxies.DOB.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static testsuite.proxies.DOB initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testsuite.proxies.DOB(context, mendixObject);
	}

	public static testsuite.proxies.DOB load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testsuite.proxies.DOB.initialize(context, mendixObject);
	}

	public static java.util.List<testsuite.proxies.DOB> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testsuite.proxies.DOB> result = new java.util.ArrayList<testsuite.proxies.DOB>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestSuite.DOB" + xpathConstraint))
			result.add(testsuite.proxies.DOB.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of day
	 */
	public final String getday()
	{
		return getday(getContext());
	}

	/**
	 * @param context
	 * @return value of day
	 */
	public final String getday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.day.toString());
	}

	/**
	 * Set value of day
	 * @param day
	 */
	public final void setday(String day)
	{
		setday(getContext(), day);
	}

	/**
	 * Set value of day
	 * @param context
	 * @param day
	 */
	public final void setday(com.mendix.systemwideinterfaces.core.IContext context, String day)
	{
		getMendixObject().setValue(context, MemberNames.day.toString(), day);
	}

	/**
	 * @return value of month
	 */
	public final String getmonth()
	{
		return getmonth(getContext());
	}

	/**
	 * @param context
	 * @return value of month
	 */
	public final String getmonth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.month.toString());
	}

	/**
	 * Set value of month
	 * @param month
	 */
	public final void setmonth(String month)
	{
		setmonth(getContext(), month);
	}

	/**
	 * Set value of month
	 * @param context
	 * @param month
	 */
	public final void setmonth(com.mendix.systemwideinterfaces.core.IContext context, String month)
	{
		getMendixObject().setValue(context, MemberNames.month.toString(), month);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dOBMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testsuite.proxies.DOB that = (testsuite.proxies.DOB) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestSuite.DOB";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
